version: '3.8'

services:
  scheduler_app:
    build: .
    container_name: exam_scheduling_system
    # Mount the current directory to /app in the container
    volumes:
      - .:/app
    # Default command to run when the container starts
    command: python src/main.py