"""
Application theme constants.
Contains color tokens, typography sizes, and shared spacing/button metrics.
"""

# ===== COLOR PALETTE =====
# PRIMARY - blue accent
PRIMARY_COLOR = "#2563EB"
# Light tints for hover/ selected states
PRIMARY_LIGHT = "#EFF6FF"
PRIMARY_DARK = "#1D4ED8"
PRIMARY_DARKER = "#1E40AF"

# SUCCESS - green for positive actions
SUCCESS_COLOR = "#16A34A"
SUCCESS_LIGHT = "#F0FDF4"
SUCCESS_DARK = "#15803D"
SUCCESS_DARKER = "#166534"

# DANGER - red for destructive actions and validation errors
DANGER_COLOR = "#EF4444"
DANGER_LIGHT = "#FEF2F2"
DANGER_DARK = "#DC2626"
DANGER_DARKER = "#991B1B"

# COURSE TYPE BADGES
# Obligatory
OBLIGATORY_BG = "#EEF2FF"
OBLIGATORY_TEXT = "#4338CA"
OBLIGATORY_BORDER = "#C7D2FE"
# Elective
ELECTIVE_BG = "#FFFBEB"
ELECTIVE_TEXT = "#92400E"
ELECTIVE_BORDER = "#FDE68A"

# BACKGROUND & SURFACES
# overall app background
BG_SURFACE = "#F8FAFC" 
# card / panel background
BG_CARD = "#FFFFFF" 
# hover state on list rows            
BG_HOVER = "#F1F5F9"  
# kept for backwards compat          
BG_DARK_SECONDARY = "#F8FAFC" 
# kept for backwards compat  
BG_DARK_TERTIARY = "#F1F5F9"    
# kept for backwards compat
BG_DARK_PRIMARY = "#F8FAFC"
# kept for backwards compat     
BG_DARK_SURFACE = "#F8FAFC"     

# TYPOGRAPHY COLORS
TEXT_PRIMARY = "#111827"
TEXT_SECONDARY = "#374151"
TEXT_TERTIARY = "#6B7280"
TEXT_MUTED = "#9CA3AF"

# BORDERS & DIVIDERS
BORDER_LIGHT = "#E5E7EB"
BORDER_LIGHTER = "#F3F4F6"

# INLINE ERROR STATES
ERROR_BG = "#FEF2F2"
ERROR_BORDER = "#FCA5A5"
ERROR_TEXT = "#DC2626"

# BUTTON VARIANTS - Secondary: white background with light border
BUTTON_SECONDARY_BG = "#FFFFFF"
BUTTON_SECONDARY_TEXT = "#374151"
BUTTON_SECONDARY_BORDER = "#E5E7EB"
BUTTON_SECONDARY_HOVER_BG = "#F9FAFB"
BUTTON_SECONDARY_HOVER_BORDER = "#D1D5DB"
BUTTON_SECONDARY_PRESSED_BG = "#F3F4F6"
BUTTON_SECONDARY_PRESSED_BORDER = "#9CA3AF"

# DISABLED STATES
DISABLED_BG = "#F3F4F6"
DISABLED_TEXT = "#9CA3AF"
DISABLED_BORDER = "#E5E7EB"

# SPINNER/LOADING INDICATOR
SPINNER_COLOR = "#2563EB"
# Error indicator icon
ICON_ERROR = "#EF4444"
# Header/day names
HEADER_TEXT = TEXT_MUTED
# Calendar grid lines
CALENDAR_GRID = BORDER_LIGHT

# NEUTRAL COLORS
NEUTRAL_BG = "#F3F4F6"
NEUTRAL_TEXT = "#374151"
NEUTRAL_BORDER = "#D1D5DB"

# ===== TYPOGRAPHY =====
FONT_FAMILY = "Segoe UI, sans-serif"
FONT_SIZE_XS = 10
FONT_SIZE_SM = 12
FONT_SIZE_MD = 14
FONT_SIZE_LG = 16
FONT_SIZE_XL = 18
FONT_SIZE_XXL = 24
FONT_WEIGHT_NORMAL = 400
FONT_WEIGHT_MEDIUM = 500
FONT_WEIGHT_BOLD = 700

# ===== BUTTON METRICS =====
BUTTON_BORDER_RADIUS = 8
PILL_BORDER_RADIUS = 100
BUTTON_PADDING_HORIZONTAL = 24

# Default large variants
BUTTON_PADDING_VERTICAL = 12
BUTTON_MIN_HEIGHT = 40

# Generic compact/small variants
BUTTON_PADDING_VERTICAL_SM = 6
BUTTON_MIN_HEIGHT_SM = 32

# ===== SPACING =====
SPACING_SMALL = 8
SPACING_MEDIUM = 12
SPACING_LARGE = 16
SPACING_XL = 24

# ===== ERROR BANNER METRICS =====
ERROR_ICON_SIZE = 16
BANNER_PADDING_X = 16
BANNER_PADDING_Y = 12
BANNER_PADDING_RIGHT = 12
BANNER_BORDER_RADIUS = 8
BANNER_BUTTON_RADIUS = 4
BANNER_SPACING = 12
BANNER_BTN_SIZE = 32
BANNER_FONT_WEIGHT = 500
BANNER_BTN_FONT_SIZE = 16
BANNER_BTN_FONT_WEIGHT = "bold"
BANNER_BORDER_WIDTH = 1

# ===== SPINNER METRICS =====
QT_ANGLE_UNIT = 16  # Qt arc angles are in 1/16-degree units
SPINNER_LINE_WIDTH = 3
SPINNER_PADDING = 4
SPINNER_ARC_ANGLE = 90
SPINNER_TIMER_INTERVAL = 20
SPINNER_SIZE = 50

# ===== TYPE BADGE METRICS =====
BADGE_RADIUS = 6
BADGE_PADDING_Y = 6
BADGE_PADDING_X = 12
BADGE_FONT_SIZE = 12
BADGE_FONT_WEIGHT = "bold"
BADGE_BORDER_WIDTH = 1
